language: ruby
rvm:
  - 2.2

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Follows advice of https://github.com/jekyll/jekyll/issues/3480
install:
  - gem install jekyll
  - gem install html-proofer

script:
  - jekyll build
  - htmlproofer _site
