language: ruby
rvm:
- 2.1

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Follows advice of https://github.com/jekyll/jekyll/issues/3480
install:
  - gem install jekyll
  - gem install html-proofer
script:
  - jekyll build
  - htmlproof _site
